export const users = [
    {
        "userEmail": "bigjez@jez.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Jez",
        "userLastName": "Lettuce",
        "userAddressLine1": "22 Park Lane",
        "userAddressLine2": "London",
        "userPostcode": "w1k 1be",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "oldmcd@hotmail.com",
        "userPassword": "sl3verence.666",
        "userFirstName": "Sleve ",
        "userLastName": "McDichael",
        "userAddressLine1": "4 Lark Close",
        "userAddressLine2": "London",
        "userPostcode": "sw18 4wr",
        "userContactNumber":"07915543221",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "goingsweemingly@yahoo.com",
        "userPassword": "$rodents4dayz",
        "userFirstName": "Onson",
        "userLastName": "Sweemey",
        "userAddressLine1": "11 Gleeming Crescent",
        "userAddressLine2": "Harlow",
        "userPostcode": "ha3 4rt",
        "userContactNumber":"07925 542949",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "tolismor@gmail.com",
        "userPassword": "Br1nksm4n235?",
        "userFirstName": "Anatoli",
        "userLastName": "Smorin",
        "userAddressLine1": "111 franklin grove",
        "userAddressLine2": "Dalston",
        "userPostcode": "n20 3ll",
        "userContactNumber":"07245 113493",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "rey0fsunshine@aol.com",
        "userPassword": "amex999!!00",
        "userFirstName": "Rey",
        "userLastName": "McSriff",
        "userAddressLine1": "5 grove street",
        "userAddressLine2": "Los Santos",
        "userPostcode": "cv31 2lk",
        "userContactNumber":"07890 321321",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "admin@glenellynpizza.chomp",
        "userPassword": "dollar$Lic3",
        "userFirstName": "Admin",
        "userLastName": "GlenEllyn",
        "userAddressLine1": "1 Fictional Pizza",
        "userAddressLine2": "Restaurant",
        "userPostcode": "n1 3bb",
        "userContactNumber":"07711 667818",
        "userAdmin" : true,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "dusty@outlook.com",
        "userPassword": "dusTice4All!",
        "userFirstName": "Willie",
        "userLastName": "Dustice",
        "userAddressLine1": "32 Pork Scratching Lane",
        "userAddressLine2": "Wood Green",
        "userPostcode": "n223ld",
        "userContactNumber":"07722454001",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "karlDanders@protonmail.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Karl",
        "userLastName": "Dandleton",
        "userAddressLine1": "211 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"0773 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "fizzychamgerlain@chomp.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Jessica",
        "userLastName": "Chamgerlain",
        "userAddressLine1": "212 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "seinfeld@lol.nyc",
        "userPassword": "Radicchio212!",
        "userFirstName": "Elaine",
        "userLastName": "Benes",
        "userAddressLine1": "213a Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "bonza@yahoo.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Todd",
        "userLastName": "Bonzalez",
        "userAddressLine1": "214 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "marthtruk@aol.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Martha",
        "userLastName": "Truk",
        "userAddressLine1": "111 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "bb1966@burton.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Barry",
        "userLastName": "Burton",
        "userAddressLine1": "122 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "sein@tastystuff.au",
        "userPassword": "Radicchio212!",
        "userFirstName": "Sarah",
        "userLastName": "Seinfeld",
        "userAddressLine1": "313 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "cazgraun@outlook.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Cary",
        "userLastName": "Graünt",
        "userAddressLine1": "545 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "fieldofdreams@hotmail.co.uk",
        "userPassword": "Radicchio212!",
        "userFirstName": "Betty",
        "userLastName": "Field",
        "userAddressLine1": "10 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "waynes@waynes.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Raul",
        "userLastName": "Waynes",
        "userAddressLine1": "5 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "blaircullen@outlook.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Blair",
        "userLastName": "Cullen",
        "userAddressLine1": "42 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "raddichio@linkedin.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Claire-Rose",
        "userLastName": "Radicchio",
        "userAddressLine1": "54 Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    },
    {
        "userEmail": "bobbob@aol.com",
        "userPassword": "Radicchio212!",
        "userFirstName": "Bob",
        "userLastName": "Bobson",
        "userAddressLine1": "1a Generic Place",
        "userAddressLine2": "Islington",
        "userPostcode": "N1 7ak",
        "userContactNumber":"07753 492244",
        "userAdmin" : false,
        "userPaymentDetails" : []
    }
]